import { X, Shield, Image, FileText, AlertCircle } from 'lucide-react';

interface HelpModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function HelpModal({ isOpen, onClose }: HelpModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl">
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="bg-gradient-to-br from-blue-600 to-cyan-500 p-2 rounded-lg">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <h2 className="text-xl font-bold text-gray-900">How It Works</h2>
          </div>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="p-6 space-y-6">
          <section>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">About This Tool</h3>
            <p className="text-gray-700 leading-relaxed">
              The AI Content Authenticity Verifier uses advanced detection algorithms to analyze images and text, determining the likelihood that content was generated by artificial intelligence versus created by humans.
            </p>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center space-x-2">
              <Image className="w-5 h-5 text-blue-600" />
              <span>Image Analysis</span>
            </h3>
            <div className="space-y-3 text-gray-700">
              <p>Our system examines multiple factors to detect AI-generated images:</p>
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li>GAN fingerprint patterns in pixel distribution</li>
                <li>Unnatural lighting and shadow inconsistencies</li>
                <li>Texture smoothness and rendering artifacts</li>
                <li>Frequency domain analysis for compression signatures</li>
                <li>Metadata patterns matching known AI generators</li>
              </ul>
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mt-4">
                <p className="text-sm">
                  <strong>Heatmap Feature:</strong> Red areas indicate regions with higher probability of AI generation. The intensity represents the confidence level of the detection.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center space-x-2">
              <FileText className="w-5 h-5 text-blue-600" />
              <span>Text Analysis</span>
            </h3>
            <div className="space-y-3 text-gray-700">
              <p>Text analysis evaluates various linguistic patterns:</p>
              <ul className="list-disc list-inside space-y-2 pl-4">
                <li>Lexical diversity and vocabulary repetition</li>
                <li>Syntactic patterns and grammatical perfection</li>
                <li>Semantic coherence and topic consistency</li>
                <li>Perplexity scores indicating predictability</li>
                <li>Burstiness analysis of sentence complexity</li>
                <li>Stylometric markers and linguistic fingerprints</li>
              </ul>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">Understanding Scores</h3>
            <div className="space-y-3">
              <div className="flex items-start space-x-3 bg-red-50 border border-red-200 rounded-lg p-4">
                <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-semibold text-red-900">70-100%: Likely AI-Generated</p>
                  <p className="text-sm text-red-700 mt-1">
                    High confidence that the content was created by AI
                  </p>
                </div>
              </div>
              <div className="flex items-start space-x-3 bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                <AlertCircle className="w-5 h-5 text-yellow-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-semibold text-yellow-900">30-70%: Uncertain</p>
                  <p className="text-sm text-yellow-700 mt-1">
                    Mixed signals or borderline characteristics
                  </p>
                </div>
              </div>
              <div className="flex items-start space-x-3 bg-green-50 border border-green-200 rounded-lg p-4">
                <AlertCircle className="w-5 h-5 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="font-semibold text-green-900">0-30%: Likely Human-Created</p>
                  <p className="text-sm text-green-700 mt-1">
                    High confidence that the content was created by humans
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-lg font-semibold text-gray-900 mb-3">Tips for Best Results</h3>
            <ul className="list-disc list-inside space-y-2 text-gray-700 pl-4">
              <li>Use high-quality images for more accurate detection</li>
              <li>Provide at least 50 words of text for meaningful analysis</li>
              <li>Results are most reliable with unedited, original content</li>
              <li>Consider multiple factors, not just the score</li>
            </ul>
          </section>

          <section className="bg-gray-50 border border-gray-200 rounded-lg p-4">
            <p className="text-sm text-gray-700">
              <strong>Important Note:</strong> This tool provides simulated AI analysis for demonstration purposes only. Results should not be used as definitive proof of content authenticity in critical applications.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
